# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            DataMary
tagline:          'Data Science'
description:      'Data Science and more'
url:              https://bluedunes.github.io
baseurl:
excerpt_separator: <!--more-->  

paginate:         5

plugins:
  - jekyll-paginate
